dtInnovCov <- function(A, C, delta=1) {
  ## computes the covariance matrix of ey in y(t) = exp(-delta*A)y(t-delta) + ey when y
  ## is generated by (d/dt)y = -Ay + z and z is white noise with covariance matrix C.
  expminA <- padm(-A*delta)
  C <- C - expminA %*% C %*% t(expminA)
  sylvester(A, C)
}
